travis:
  secure:
    BINSTAR_TOKEN: KTL3WOEJ4gtOpeHOan96xnHSF4+/RL8mKLd3AvM33Bmdd0NqxOM3zdcRug/GiZrZ0215GIwvH0qKb5DPSKeQIvYrJQoToVm2khxbFXay9G8178P65IsYEqipQ76zSDVDazZaac/D9h/VKuJ7xy25vVKhPx9g4KckTn03eQsc8lFs0HOzSyVwKeG9G15hA8z9ZF73sa+zfX6YhjRV1nl2mh+imVKHMyrNsfRHhuv6jF2mrNIKqb8K6WmftcbfS1N0gujusZNReRmiYyFaYzB4i16zfpFOalwIDxnpZM53w43C2Y6P1tGUo6wjCFpCr7q0eA5F3FJqZ9J1gcTNshuXbvM+qxbx1LOKoDwsoUXMGINx/Padbaw/nvK/C+WStovZHHg9KVeZkUCB7aIH/uAHWYved9xn3DKmGuvmRGEjSR7TgK2tnDds/sMEKtH6GbZp0/rikSpp5y0W9iTxbGMh72eBQDV68vZdEKpxsbMI5UR57ZC/MRaxuDkWcwlPpt8G29hEy5LR3Wm4pwdyILExqKcGj29uQPHp36R9726xzv2m0fkaiC9IDpA8Hx6nFLiIDjrvNp9pR+s6aEttYoBhWLjrH8qTqAnfT/RQXxP8xgTLQqkfv5uMtIayuF7PBJhq6aL6NHsqqmSzQSm68J4DP2lijmC5akMNnEdJVWav1j0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
